sonar.projectKey=PoweredBySymfony_xaviertrouche_e0f30abd-29e5-4cc5-a1ba-ba6b7500c144
sonar.projectName=xaviertrouche
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,.next/**,coverage/**,**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.app.json
